version: "3.7"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - ito-network

  ito-upload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - ito-network
    depends_on:
      - mongodb

networks:
  ito-network:

volumes:
  db-data: